### ISSUE TITLE
Version minimale OGSpy Manquante

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/mod-majvisu#2]

**Comment by Nephilas** [comment]
Hello à toute la team

Comme je le disais hier à DarkNoon, il est impossible d'installer le MOD depuis la version 3.3.4
Nous recevons une message d'erreur disant que la version minimale d'OGS n'est pas installée

Merci d'avance

Nephilas
![etat serveur](https://user-images.githubusercontent.com/44340099/47289361-ab765780-d5fa-11e8-94a4-1c9c1e3f9567.JPG)

**Comment by Roms0406** [comment]
Ça sent le même problème que le mod inactifs ça ;)

**Comment by darknoon29** [comment]
@Roms0406 Tu veux le corriger ?
Il suffit d'ajouter la version mini d'ogspy dans le versio.txt et de monter d'une version le mod

**Comment by Roms0406** [comment]
Bon j'ai tout fait comme on m'a dit ^^
Testé la maj sous ogspy 3.3.4 installation réussie chez moi, voir le retour de nephilas maintenant

**Comment by Nephilas** [comment]
Désolé du retard voila que je rentre du travail ^^

Je viens de l'installer avec succès et tout fonctionne correctement ;-)

Merci à la Team encore une fois :P

**Comment by darknoon29** [comment]
Super Merci à @Roms0406 qui a fait la modif !
