### ISSUE TITLE
Echo dans code HTML

### ISSUE THREAD

**Issue by Athar42** [OGSteam/mod-majvisu#3]
Dans le fichier "maj.php", ligne 65, un echo est déclaré:

`echo '<script src="http://www.ogsteam.besaba.com/js/stat.js" type="text/javascript"> </script>';`

Deux petits problèmes:
- Il est déclaré dans le HTML direct, et non dans une balise PHP
- Le lien vers le fichier .JS est mort

Si ce mod est encore en vie, une petite modif rapide à faire donc :)

**Comment by darknoon29** [comment]
A supprimer oui

**Comment by machine62** [comment]
fait #377173a
